// Generated by gencpp from file fla_msgs/Keypoint.msg
// DO NOT EDIT!


#ifndef FLA_MSGS_MESSAGE_KEYPOINT_H
#define FLA_MSGS_MESSAGE_KEYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fla_msgs
{
template <class ContainerAllocator>
struct Keypoint_
{
  typedef Keypoint_<ContainerAllocator> Type;

  Keypoint_()
    : id(0)
    , x(0.0)
    , y(0.0)  {
    }
  Keypoint_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::fla_msgs::Keypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fla_msgs::Keypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Keypoint_

typedef ::fla_msgs::Keypoint_<std::allocator<void> > Keypoint;

typedef boost::shared_ptr< ::fla_msgs::Keypoint > KeypointPtr;
typedef boost::shared_ptr< ::fla_msgs::Keypoint const> KeypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fla_msgs::Keypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fla_msgs::Keypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fla_msgs::Keypoint_<ContainerAllocator1> & lhs, const ::fla_msgs::Keypoint_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fla_msgs::Keypoint_<ContainerAllocator1> & lhs, const ::fla_msgs::Keypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fla_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fla_msgs::Keypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fla_msgs::Keypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fla_msgs::Keypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fla_msgs::Keypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fla_msgs::Keypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fla_msgs::Keypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fla_msgs::Keypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8a73f27507e9626faa0d25bacb6ecf2";
  }

  static const char* value(const ::fla_msgs::Keypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8a73f27507e9626ULL;
  static const uint64_t static_value2 = 0xfaa0d25bacb6ecf2ULL;
};

template<class ContainerAllocator>
struct DataType< ::fla_msgs::Keypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fla_msgs/Keypoint";
  }

  static const char* value(const ::fla_msgs::Keypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fla_msgs::Keypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# (x, y) define the keypoint location in pixel coordinates\n"
"uint32 id\n"
"float32 x \n"
"float32 y\n"
;
  }

  static const char* value(const ::fla_msgs::Keypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fla_msgs::Keypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fla_msgs::Keypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fla_msgs::Keypoint_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLA_MSGS_MESSAGE_KEYPOINT_H
