# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fla_msgs/JoyDef.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JoyDef(genpy.Message):
  _md5sum = "e5483257fd0a1adbc2dd471d331e6470"
  _type = "fla_msgs/JoyDef"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Message defining constants for the wireless joysticks used by ACL

# buttons
int64 A=0
int64 B=1
int64 X=2
int64 Y=3
int64 LB=4
int64 RB=5
int64 BACK=6
int64 START=7
int64 CENTER=8 # center 'on' button
int64 LS=9 # left joystick
int64 RS=10 # right joystick
int64 LEFT=11
int64 RIGHT=12
int64 UP=13
int64 DOWN=14

# axes
int64 LEFT_X=0
int64 LEFT_Y=1
int64 LT=2
int64 RIGHT_X=3
int64 RIGHT_Y=4
int64 RT=5
"""
  # Pseudo-constants
  A = 0
  B = 1
  X = 2
  Y = 3
  LB = 4
  RB = 5
  BACK = 6
  START = 7
  CENTER = 8
  LS = 9
  RS = 10
  LEFT = 11
  RIGHT = 12
  UP = 13
  DOWN = 14
  LEFT_X = 0
  LEFT_Y = 1
  LT = 2
  RIGHT_X = 3
  RIGHT_Y = 4
  RT = 5

  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JoyDef, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
