# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fla_msgs/NodeList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fla_msgs.msg
import genpy

class NodeList(genpy.Message):
  _md5sum = "ef5328a9c9c28a94588f0215d3bce4ca"
  _type = "fla_msgs/NodeList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
NodeStatus[] nodelog

================================================================================
MSG: fla_msgs/NodeStatus
uint8 INACTIVE=1
uint8 STARTING=2
uint8 INIT=3
uint8 READY=4
uint8 ALARM=5
uint8 FAIL=6
uint8 SILENT=7
uint32 id
uint32 pid
uint8 status
int32 arg
float64 load
"""
  __slots__ = ['stamp','nodelog']
  _slot_types = ['time','fla_msgs/NodeStatus[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,nodelog

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NodeList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.nodelog is None:
        self.nodelog = []
    else:
      self.stamp = genpy.Time()
      self.nodelog = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.stamp.secs, _x.stamp.nsecs))
      length = len(self.nodelog)
      buff.write(_struct_I.pack(length))
      for val1 in self.nodelog:
        _x = val1
        buff.write(_get_struct_2IBid().pack(_x.id, _x.pid, _x.status, _x.arg, _x.load))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.nodelog is None:
        self.nodelog = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.nodelog = []
      for i in range(0, length):
        val1 = fla_msgs.msg.NodeStatus()
        _x = val1
        start = end
        end += 21
        (_x.id, _x.pid, _x.status, _x.arg, _x.load,) = _get_struct_2IBid().unpack(str[start:end])
        self.nodelog.append(val1)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.stamp.secs, _x.stamp.nsecs))
      length = len(self.nodelog)
      buff.write(_struct_I.pack(length))
      for val1 in self.nodelog:
        _x = val1
        buff.write(_get_struct_2IBid().pack(_x.id, _x.pid, _x.status, _x.arg, _x.load))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.nodelog is None:
        self.nodelog = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.nodelog = []
      for i in range(0, length):
        val1 = fla_msgs.msg.NodeStatus()
        _x = val1
        start = end
        end += 21
        (_x.id, _x.pid, _x.status, _x.arg, _x.load,) = _get_struct_2IBid().unpack(str[start:end])
        self.nodelog.append(val1)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2IBid = None
def _get_struct_2IBid():
    global _struct_2IBid
    if _struct_2IBid is None:
        _struct_2IBid = struct.Struct("<2IBid")
    return _struct_2IBid
